### ISSUE TITLE
Import of module is not working

### ISSUE THREAD

**Issue by heliolino** [torgro/cliMenu#1]
hello, 
 I downloaded the module from powershell gallery 
 with command "Install-Module -Name CliMenu" 

 when tried to run the example script it says that show-menu is not a recognized cmdlet;
 where  the show-menu is coming from ? 

 is there any other item necessary to have the CliMenu to work ? 
any dependent object or module ?

**Comment by torgro** [comment]
hi, Sorry about your issue. No,  there are no dependencies for the module. Are you sure it got installed? Try doing Get-Module -Listavailable | Where Name -like cli*

Just tried it on a Win10 VM and installed it from the gallery. It "worked" by displaying a warning that you have not created a menu. The Show-Menu is a cmdlet/function in the module, defined in the climenu.psm1 file.

Cheers 
Tore

**Comment by heliolino** [comment]
Hi Tore, 
 i made some improvements on the analysis, 
 First, trying to use the Show-menu is only possible if load-module statement is the first on the script. 

 i have used your Example.ps1 file as a test, and the following issue appears 

Method invocation failed because [System.Management.Automation.PSCustomObject] doesn't contain a method named 'Where'.
At C:\test\CliMenu\CliMenu.psm1:166 char:9
-         $script:Menus.Where({$_.IsMainMenu -eq $true})
-         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (Where:String) [], RuntimeException
  - FullyQualifiedErrorId : MethodNotFound

---

## have you seem similar problem ? 

current PS version, $PSVersionTable

Name                           Value

---

PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.2.9200.16398
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2

**Comment by torgro** [comment]
hi,

That explains it. You are running PS 3. The where method was introduced in PS 4. You should probably consider moving towards a newer version. Sorry!

Cheers

Tore

**Comment by heliolino** [comment]
Tore, 

 after upgrade to PS4, it worked like a charm , 
 thanks.
