### ISSUE TITLE
Submenu with multiple items

### ISSUE THREAD

**Issue by natcoso9955** [torgro/cliMenu#2]
Hey so i have been messing around with this powershell module for abit and cant seem to figure this out.
I cant seem to add a submenu with multiple items. When i try it other doesnt show them or the script crashes.

Can you please provide the code for creating a submenu with 2 submenu items that do different things.

Thankyou.

**Comment by torgro** [comment]
hi,

If you look in ([Example1.ps1](https://github.com/torgro/cliMenu/blob/master/Scripts/Example.ps1)) you will find an example menu with a submenu. To add an item to the submenu, you can do this:

```powershell
$newSubMenu = @{
    Name = "The name"
    DisplayName = "Do something usefull"
    Action = {Show-Command -Name write-host}
}

Get-Menu -Name submenu | New-MenuItem @newSubMenu -DisableConfirm
```

Cheers Tore
